project:
  type: book

book:
  title: "A Practitioner's Guide to Financial Market Analysis"
  author: "Ken Nyholm"
  date: "3/29/2026"
  chapters:
    - index.qmd 
    - intro.qmd
    - DBPensions.qmd 
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



